from io import BytesIO

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer


def create_pdf(review: dict):
    """
    Generates a PDF report from the AI review.
    """

    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    story = []

    # -----------------------------
    # Title
    # -----------------------------
    story.append(
        Paragraph(
            "AI Software Review Report",
            styles["Title"]
        )
    )

    story.append(Spacer(1, 20))

    # -----------------------------
    # Score
    # -----------------------------
    story.append(
        Paragraph(
            f"<b>Overall Score:</b> {review.get('score', '-')}/10",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1, 15))

    # -----------------------------
    # Summary
    # -----------------------------
    story.append(
        Paragraph(
            "<b>Summary</b>",
            styles["Heading2"]
        )
    )

    story.append(
        Paragraph(
            review.get("summary", "No Summary"),
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 15))

    # -----------------------------
    # Helper Function
    # -----------------------------
    def add_section(title, items):

        story.append(
            Paragraph(
                f"<b>{title}</b>",
                styles["Heading2"]
            )
        )

        if not items:

            story.append(
                Paragraph(
                    "None",
                    styles["BodyText"]
                )
            )

        else:

            for item in items:

                story.append(
                    Paragraph(
                        f"• {item}",
                        styles["BodyText"]
                    )
                )

        story.append(Spacer(1, 12))

    # -----------------------------
    # Sections
    # -----------------------------
    add_section("Bugs", review.get("bugs", []))

    add_section("Security Issues", review.get("security", []))

    add_section("Performance Improvements", review.get("performance", []))

    add_section("Code Quality", review.get("quality", []))

    add_section("PEP8 Issues", review.get("pep8", []))

    # -----------------------------
    # Footer
    # -----------------------------
    story.append(Spacer(1, 25))

    story.append(
        Paragraph(
            "Generated by AI Software Review Platform",
            styles["Italic"]
        )
    )

    # Build PDF
    doc.build(story)

    buffer.seek(0)

    return buffer